#!/usr/bin/env bash

echo 'Macbook dotfiles install initiated.'

fish -c 'set -U MACBOOK true'

./update-zshrc

./install fd fish git tmux vim kitty scripts lf javascript

echo 'Macbook dotfiles install complete.'


