#!/usr/bin/env bash

# if in wsl, copy wslconfig to windows home folder
if [[ -x "$(command -v wslpath)" ]]; then
    echo 'Replacing the .wslconfig file in the windows home directory.'

    WINHOME=$(wslpath "$(wslvar USERPROFILE)")

    cp ~/.dotfiles/.wslconfig $WINHOME/.wslconfig
fi

