#!/usr/bin/env bash

# This installs the fonts successfully, but there may be something further wrong with gnome-terminal compatibility and spacing.
mkdir -p ~/.local/share/fonts
# cp "$HOME/.dotfiles/fonts/Iosevka Term Nerd Font Complete Mono.ttf" ~/.local/share/fonts/.
cp "$HOME/.dotfiles/fonts/Sauce Code Pro Medium Nerd Font Complete Mono.ttf" ~/.local/share/fonts/.
fc-cache -f -v
# fc-list | grep Iosevka
fc-list | grep Sauce

