#!/usr/bin/env bash

# if in wsl, run commands
if [[ -x "$(command -v wslpath)" ]]; then
    WINHOME=$(wslpath "$(wslvar USERPROFILE)")

    echo 'Replacing the .wslconfig file in the windows home directory.'
    cp ~/.dotfiles/non-stowed-copied-files/.wslconfig $WINHOME/.wslconfig

    echo 'Replacing the current windows terminal settings.json file with the .windows-terminal-config.json'
    cp ~/.dotfiles/non-stowed-copied-files/.windows-terminal-config.json $WINHOME/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
    cp ~/.dotfiles/non-stowed-copied-files/.windows-terminal-config.json $WINHOME/AppData/Local/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe/LocalState/settings.json

    echo 'Replacing the .vimrc file in the windows home directory.'
    cp ~/.dotfiles/vim/.vimrc $WINHOME/.vimrc

    echo 'Replacing the .gitconfig in the windows home directory'
    cp ~/.gitconfig $WINHOME/.gitconfig

    echo 'Replacing the .bashrc in the windows home directory'
    cp ~/.bashrc $WINHOME/.bashrc
fi

