#!/usr/bin/env bash

cd $HOME/.dotfiles

# Clean symlinks if they exist
for dir in "$@"; do
    stow -v --delete $dir
done

# Ensure dirs we don't want symlinked exist on the off chance they don't
mkdir -p ~/.config/fish/functions
mkdir -p ~/.config/fish/completions
mkdir -p ~/.config/fish/conf.d
mkdir -p ~/.config/mise/
mkdir -p ~/.local/bin/

# Create the symlinks
for dir in "$@"; do
    stow -v $dir
done

echo 'Replacing the .gitconfig in the home directory.'
cp ~/.dotfiles/non-stowed-copied-files/.gitconfig ~/.gitconfig

