#!/usr/bin/env bash

echo 'Updating .bashrc by appending or creating file with custom values.'

# delete everything from mentioned line to end of file
sed -i '/Appended to .bashrc by Chris/,$d' ~/.bashrc &> /dev/null

# re-append to end of .bashrc
cat ~/.dotfiles/non-stowed-copied-files/.bashrc >> ~/.bashrc

