#!/usr/bin/env bash

#If in an XRDP session
if env | grep 'XRDP' > /dev/null; then
    # Set wallpaper
    $HOME/.fehbg
else
    # default to single monitor
    # ~/.config/i3/xrandr-scripts/set-dp-single-monitor
    ~/.config/i3/xrandr-scripts/set-single-monitor

    # Set wallpaper
    $HOME/.fehbg

    # Lock immediately after auto-login on startup
    i3lock --color=006180
fi
