#!/usr/bin/env bash
# HDMI-0 3840x2160
# DP-4 1920x1080

# xrandr --dpi 192 --fb 3840x2160 \
#     --output HDMI-A-0 --scale 2x2 --primary --mode 1920x1080 -r 165.00 \
#     --output DisplayPort-2 --off
#
# xrandr --dpi 192 --fb 3840x2160 \
#     --output  DisplayPort-2 --scale 1x1 --mode 3840x2160 --primary -r 144.00
#
xrandr --dpi 192 --fb 3840x2160 \
    --output HDMI-A-0 --scale 1x1 --mode 3840x2160 --primary -r 120.00
