#!/usr/bin/env bash
# HDMI-0 3840x2160
# DP-4 1920x1080

xrandr --dpi 192 --fb 3840x2160 \
    --output DisplayPort-2 --scale 1x1 --mode 3840x2160 --primary --pos 3840x0

# xrandr --output DisplayPort-2 --scale 1x1 --primary

# xrandr --dpi 192 --fb 3840x2160 \
#     --output DisplayPort-2 --scale 0.9999x0.9999 --mode 3840x2160 --primary --pos 3840x0









# xrandr --dpi 192 --fb 7680x2160 \
#     --output DP-4 --scale 2x2 \
#     --output HDMI-0 --mode 3840x2160 --primary --pos 3840x0

# xrandr --dpi 192 --fb 3840x2160 \
#     --output DP-4 --scale 2x2 --primary \
#     --output HDMI-0 --off







# xrandr --dpi 192 --fb 7680x4320 \
#     --output HDMI-0 --mode 3840x2160 \
#     --output DP-4 --scale 2x2 --pos 3840x0 --panning 3840x2160+3840+0

# xrandr --dpi 192 --fb 7680x2160 \
#     --output HDMI-0 --off \
#     --output DP-4 --primary --scale 2x2 --pos 0x0 --panning 3840x2160








# xrandr --dpi 192 --fb 7680x4320 \
#     --output HDMI-0 --mode 3840x2160 \
#     --output DP-4 --scale 2x2 --pos 3840x0 --panning 3840x2160+3840+0

# xrandr --dpi 192 --fb 3840x2160 \
#     --output HDMI-0 --off \
#     --output DP-4 --scale 2x2 --panning 3840x2160




# xrandr --dpi 276 --fb 7040x3960 \
#     --output eDP-1 --mode 3200x1800 \
#     --output DP-1-2 --scale 2x2 --pos 3200x0 --panning 3840x2160+3200+0

# xrandr --dpi 276 --fb 3840x2160 \
#     --output eDP-1 --off \
#     --output DP-1-2 --scale 2x2 --panning 3840x2160

# xrandr --output DP-0 --off \
# --output DP-1 --off \
# --output DP-2 --off \
# --output DP-3 --off \
# --output HDMI-0 --primary --mode 3840x2160 --pos 3840x0 --rotate normal \
# --output DP-4 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-5 --off

